// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {gpt} from '../models';
import {context} from '../models';

export function Send(arg1:Array<gpt.ContentType>,arg2:gpt.SendOption):Promise<any>;

export function Startup(arg1:context.Context):Promise<void>;
