// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Send(arg1, arg2) {
  return window['go']['gpt']['ChatGPT']['Send'](arg1, arg2);
}

export function Startup(arg1) {
  return window['go']['gpt']['ChatGPT']['Startup'](arg1);
}
