name: Build Matrix

on:
  pull_request:
    branches:
      - master
  # allows to run the workflow manually from the actions tab
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
              name: "Windows",
              artifact: "gpt-tools-window-amd64.tar.gz",
              executable_name: "gpt-tools.exe",
              os: windows-2022,
              build_tags: "production,desktop",
              build_platform: "windows/amd64",
            }
          - {
              name: "Ubuntu",
              artifact: "gpt-tools-linux-amd64.tar.gz",
              executable_name: "gpt-tools",
              os: ubuntu-20.04,
              build_tags: "production,desktop",
              build_platform: "linux/amd64",
            }
          - {
              name: "macOS",
              artifact: "gpt-tools-darwin-universal.tar.gz",
              executable_name: "gpt-tools.app",
              os: macos-11,
              build_tags: "production,desktop",
              build_platform: "darwin/universal",
            }
          - {
              name: "macOS",
              artifact: "gpt-tools-darwin-amd64.tar.gz",
              executable_name: "gpt-tools.app",
              os: macos-10,
              build_tags: "production,desktop",
              build_platform: "darwin/amd64",
            }
          - {
              name: "macOS",
              artifact: "gpt-tools-darwin-arm64.tar.gz",
              executable_name: "gpt-tools.app",
              os: macos-11,
              build_tags: "production,desktop",
              build_platform: "darwin/arm64",
            }

    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ">=1.18.0"

      - name: Setup NPM
        uses: actions/setup-node@v3
        with:
          node-version: 16.14.x

      - name: Setup Webkit (Linux)
        run: sudo apt update && sudo apt install -y libgtk-3-dev libwebkit2gtk-4.0-dev
        if: ${{ matrix.config.name == 'Ubuntu' }}

      - name: Setup jq (macOS)
        uses: dcarbone/install-jq-action@v1.0.1
        if: ${{ matrix.config.name == 'macOS' }}

      - name: Setup Restic
        uses: AnimMouse/setup-restic@v1

      - name: Setup Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@v2.5.0

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: wails build -tags ${{ matrix.config.build_tags }} -platform ${{ matrix.config.build_platform }}

      - name: Archive
        uses: thedoctor0/zip-release@main
        with:
          type: tar
          directory: build
          path: bin
          filename: ${{ matrix.config.artifact }}

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          path: build/${{ matrix.config.artifact }}
          name: ${{ matrix.config.artifact }}
